# Generated by Django 3.0.7 on 2020-06-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200609_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='phone_number',
            field=models.CharField(max_length=254),
        ),
    ]
